name: Build and Release (Windows Native EXE)

permissions:
  contents: write
  releases: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Check out the repository.
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (which includes both jlink and jpackage).
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Compile the Java source code.
      - name: Compile Source
        shell: cmd
        run: |
          REM Create output directory.
          mkdir out
          REM List all .java files from src into sources.txt.
          dir /b /s src\*.java > sources.txt
          REM Compile the sources into the out directory.
          javac -d out @sources.txt
          echo Compiled classes:
          dir /s out

      # 4. Package the compiled classes into a runnable JAR.
      - name: Package into JAR
        shell: cmd
        run: |
          REM Create the jar with PositionSizeCalculator as the main class.
          jar cfe PositionSizeCalculator.jar PositionSizeCalculator -C out .
          echo JAR contents:
          jar tf PositionSizeCalculator.jar

      # 5. Create a minimal runtime image using jlink (includes the java.desktop module for Swing).
      - name: Create Runtime Image with jlink
        shell: cmd
        run: |
          jlink --module-path "%JAVA_HOME%\jmods" --add-modules java.desktop --output runtime
          echo Runtime image created:
          dir runtime

      # 6. Use jpackage to create a native Windows executable.
      - name: Package Native EXE with jpackage
        shell: cmd
        run: |
          REM We use --input . so that jpackage finds PositionSizeCalculator.jar in the current directory.
          jpackage --input . --runtime-image runtime --dest . --name PositionSizeCalculator --main-jar PositionSizeCalculator.jar --main-class PositionSizeCalculator --icon calculator.ico --win-shortcut --win-menu --win-upgrade-uuid 123e4567-e89b-12d3-a456-426614174000 --type exe
          echo Packaged files:
          dir /b *.exe

      # 7. Rename the produced installer (if needed) to PositionSizeCalculator.exe.
      - name: Rename Installer if Needed
        shell: cmd
        run: |
          REM Look for any .exe file whose name contains "PositionSizeCalculator"
          for /f "delims=" %%i in ('dir /b /a-d *PositionSizeCalculator*.exe') do (
            echo Found installer: %%i
            ren "%%i" "PositionSizeCalculator.exe"
          )
          echo After renaming:
          dir /b *.exe

      # 8. Create a GitHub Release.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 9. Upload the EXE as a release asset.
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PositionSizeCalculator.exe
          asset_name: PositionSizeCalculator.exe
          asset_content_type: application/octet-stream
