name: Build and Release

# This workflow runs when you push a tag matching the pattern v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java (JDK 11 in this example).
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Create the output directory (if it does not already exist).
      - name: Create output directory
        run: mkdir -p out/production/position-size-caulculator

      # 4. Compile Java source code from the 'src' directory.
      - name: Compile Java Source
        run: |
          # Compile all .java files under src/ into the output directory
          javac -d out/production/position-size-caulculator $(find src -name "*.java")
          echo "Compilation output:"
          ls -R out/production/position-size-caulculator

      # 5. Package the compiled classes into a runnable JAR.
      - name: Package into JAR
        run: |
          # 'PositionSizeCalculator' is assumed to be your main class (adjust if necessary)
          jar cfe PositionSizeCalculator.jar PositionSizeCalculator -C out/production/position-size-caulculator .
          echo "JAR contents:"
          jar tf PositionSizeCalculator.jar

      # 6. Create a GitHub Release using the pushed tag.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 7. Upload the JAR file as a release asset.
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PositionSizeCalculator.jar
          asset_name: PositionSizeCalculator.jar
          asset_content_type: application/java-archive
