name: Build and Release (Cross‑Platform Runnable JAR)

permissions:
  contents: write

# This workflow is triggered when you push a tag matching the pattern v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up the JDK (using Temurin; adjust the version as needed).
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Compile the Java source code.
      - name: Compile Java Source
        run: |
          # Create the output directory.
          mkdir -p out
          # Find all .java files under src and list them into sources.txt.
          find src -name "*.java" > sources.txt
          # Compile the sources into the out directory.
          javac -d out @sources.txt
          echo "Compiled classes:"
          find out

      # 4. Package the compiled classes into a runnable JAR.
      - name: Package into runnable JAR
        run: |
          # The 'cfe' option creates a JAR with the specified entry point.
          jar cfe PositionSizeCalculator.jar PositionSizeCalculator -C out .
          echo "JAR contents:"
          jar tf PositionSizeCalculator.jar

      # 5. Create a GitHub Release using the pushed tag.
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 6. Upload the runnable JAR as a release asset.
      - name: Upload Release Asset (JAR)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PositionSizeCalculator.jar
          asset_name: PositionSizeCalculator.jar
          asset_content_type: application/java-archive
