name: Build and Release (Windows Self‑Contained EXE)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Compile Java Source
        shell: cmd
        run: |
          mkdir out
          dir /b /s src\*.java > sources.txt
          javac -d out @sources.txt
          echo Compiled classes:
          dir /s out

      - name: Package into JAR
        shell: cmd
        run: |
          jar cfe PositionSizeCalculator.jar PositionSizeCalculator -C out .
          echo JAR contents:
          jar tf PositionSizeCalculator.jar

      - name: Create Runtime Image
        shell: cmd
        run: |
          jlink --module-path "%JAVA_HOME%\jmods" --add-modules java.desktop --output runtime
          echo Created runtime image:
          dir runtime

      - name: Package native executable with jpackage
        shell: cmd
        run: |
          jpackage --runtime-image runtime --dest . --name PositionSizeCalculator --main-jar PositionSizeCalculator.jar --main-class PositionSizeCalculator --icon calculator.ico --win-shortcut --win-menu --type exe
          echo Packaged files:
          dir

      - name: Rename installer
        shell: cmd
        run: |
          for /f "delims=" %%i in ('dir /b /a-d *PositionSizeCalculator*.exe') do (
            echo Found installer: %%i
            ren "%%i" "PositionSizeCalculator.exe"
          )
          echo After renaming:
          dir

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (EXE)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PositionSizeCalculator.exe
          asset_name: PositionSizeCalculator.exe
          asset_content_type: application/octet-stream